# Generated by Django 5.2.1 on 2026-04-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_alter_bid_id_alter_listing_id_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="amount",
            field=models.IntegerField(default=None),
        ),
    ]
