# Generated by Django 5.2.1 on 2026-04-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_alter_bid_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="amount",
            field=models.IntegerField(),
        ),
    ]
