# Generated by Django 5.2.1 on 2026-04-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_alter_bid_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True, related_name="watchlists", to="auctions.listing"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="description",
            field=models.CharField(max_length=1024),
        ),
    ]
